# !!! A builder service must be included before this file !!!

# Define services
services:
  # CMake configure service
  gen_cmake:
    image: builder:${BUILDER_TAG}
    env_file:
      - path: .env.computed
        required: true
      - path: ${DOCKER_BASE_FOLDER}/.env.override
        required: false
    volumes:
      - ${MOUNT_POINT:?Base folder of the repository}:/home/builder/sources:ro
      - builds:/home/builder/builds
      - ~/.ssh/known_hosts:/home/builder/.ssh/known_hosts:ro
      - ${SSH_AUTH_SOCK_LOCATION:-/dev/null}:${SSH_AUTH_SOCK_LOCATION:-/dev/null}
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_LOCATION:-}
    entrypoint: /bin/bash ./gen_cmake.sh -o ../builds/${BUILD_FOLDER:?Build folder inside the persistent volume}

  # Build service
  build:
    image: builder:${BUILDER_TAG}
    env_file:
      - path: .env.computed
        required: true
      - path: ${DOCKER_BASE_FOLDER}/.env.override
        required: false
    volumes:
      - ${MOUNT_POINT:?Base folder of the repository}:/home/builder/sources:ro
      - builds:/home/builder/builds
    entrypoint: cmake --build ../builds/${BUILD_FOLDER:?Build folder inside the persistent volume}

  # Shell service
  shell:
    image: builder:${BUILDER_TAG}
    env_file:
      - path: .env.computed
        required: true
      - path: ${DOCKER_BASE_FOLDER}/.env.override
        required: false
    volumes:
      - ${MOUNT_POINT:?Base folder of the repository}:/home/builder/sources:ro
      - builds:/home/builder/builds
      - ~/.ssh/known_hosts:/home/builder/.ssh/known_hosts:ro
      - ${SSH_AUTH_SOCK_LOCATION:-/dev/null}:${SSH_AUTH_SOCK_LOCATION:-/dev/null}
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_LOCATION:-}
    entrypoint: /bin/bash

  # Run service
  run:
    image: builder:${BUILDER_TAG}
    env_file:
      - path: .env.computed
        required: true
      - path: ${DOCKER_BASE_FOLDER}/.env.override
        required: false
    volumes:
      - builds:/home/builder/builds
    entrypoint: ./${APP:?Name of the application to run}
    working_dir: /home/builder/builds/${BUILD_FOLDER:?Build folder inside the persistent volume}/Install/bin
